// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zvdzpccugecjzdgplivb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp2ZHpwY2N1Z2VjanpkZ3BsaXZiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc2MjEzNjYsImV4cCI6MjA2MzE5NzM2Nn0.WVJ6N0Bb0wCyoTpoxLiQPG6iVt82K2UUoe7ToW3ezcU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);